Revert "Upgrade node to 13.12.0"
This reverts commit a48a1e29c77e017cd2d65e4d1d3b62748aeba5be.

Apparently, Heroku doesn't support node 13.12.0 yet?

    RajivsMacBookPro:vh1 rajiv.shah$ git push heroku master
    Counting objects: 9, done.
    Delta compression using up to 8 threads.
    Compressing objects: 100% (9/9), done.
    Writing objects: 100% (9/9), 981 bytes | 981.00 KiB/s, done.
    Total 9 (delta 7), reused 0 (delta 0)
    remote: Compressing source files... done.
    remote: Building source:
    remote:
    remote: -----> React.js (create-react-app) multi app detected
    remote: =====> Downloading Buildpack:
    https://github.com/heroku/heroku-buildpack-multi.git
    remote: =====> Detected Framework: Multipack
    remote: =====> Downloading Buildpack:
    https://github.com/heroku/heroku-buildpack-nodejs.git
    remote: =====> Detected Framework: Node.js
    remote:
    remote: -----> Creating runtime environment
    remote:
    remote:        NPM_CONFIG_LOGLEVEL=error
    remote:        NODE_ENV=production
    remote:        NODE_MODULES_CACHE=true
    remote:        NODE_VERBOSE=false
    remote:
    remote: -----> Installing binaries
    remote:        engines.node (package.json):  13.12.0
    remote:        engines.npm (package.json):   6.14.4
    remote:
    remote:        Resolving node version 13.12.0...
    remote:        Could not find Node version corresponding to version
    requirement: 13.12.0
    remote:
    remote: -----> Build failed
    remote:
    remote:  !     No matching version found for Node: 13.12.0
    remote:
    remote:        Heroku supports the latest Stable version of Node.js as
    well as all
    remote:        active LTS (Long-Term-Support) versions, however you have
    specified
    remote:        a version in package.json (13.12.0) that does not
    correspond to
    remote:        any published version of Node.js.
    remote:
    remote:        You should always specify a Node.js version that matches
    the runtime
    remote:        you’re developing and testing with. To find your version
    locally:
    remote:
    remote:        $ node --version
    remote:        v6.11.1
    remote:
    remote:        Use the engines section of your package.json to specify
    the version of
    remote:        Node.js to use on Heroku. Drop the ‘v’ to save only the
    version number:
    remote:
    remote:        "engines": {
    remote:          "node": "6.11.1"
    remote:        }
    remote:
    remote:        https://help.heroku.com/6235QYN4/
    remote:
    remote:  !     Push rejected, failed to compile React.js
    (create-react-app) multi app.
    remote:
    remote:  !     Push failed
    remote: Verifying deploy...
    remote:
    remote: !   Push rejected to vh1.
    remote:
    To https://git.heroku.com/vh1.git
     ! [remote rejected] master -> master (pre-receive hook declined)
     error: failed to push some refs to 'https://git.heroku.com/vh1.git'